/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.demo.api;

import com.example.demo.model.Workout;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-08T12:59:20.852239Z[Etc/UTC]")
@Validated
@Tag(name = "workouts", description = "the workouts API")
public interface WorkoutsApi {

    default WorkoutsApiDelegate getDelegate() {
        return new WorkoutsApiDelegate() {};
    }

    /**
     * GET /workouts : Get all workouts
     *
     * @return A list of workouts (status code 200)
     */
    @Operation(
        operationId = "workoutsGet",
        summary = "Get all workouts",
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of workouts", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Workout.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/workouts",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Workout>> workoutsGet(
        
    ) {
        return getDelegate().workoutsGet();
    }


    /**
     * GET /workouts/{id} : Get a specific workout by ID
     *
     * @param id ID of the workout (required)
     * @return A single workout (status code 200)
     *         or Workout not found (status code 404)
     */
    @Operation(
        operationId = "workoutsIdGet",
        summary = "Get a specific workout by ID",
        responses = {
            @ApiResponse(responseCode = "200", description = "A single workout", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Workout.class))
            }),
            @ApiResponse(responseCode = "404", description = "Workout not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/workouts/{id}",
        produces = { "application/json" }
    )
    default ResponseEntity<Workout> workoutsIdGet(
        @Parameter(name = "id", description = "ID of the workout", required = true) @PathVariable("id") String id
    ) {
        return getDelegate().workoutsIdGet(id);
    }


    /**
     * POST /workouts : Create a new workout
     *
     * @param workout  (required)
     * @return Workout created successfully (status code 201)
     */
    @Operation(
        operationId = "workoutsPost",
        summary = "Create a new workout",
        responses = {
            @ApiResponse(responseCode = "201", description = "Workout created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Workout.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/workouts",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Workout> workoutsPost(
        @Parameter(name = "Workout", description = "", required = true) @Valid @RequestBody Workout workout
    ) {
        return getDelegate().workoutsPost(workout);
    }

}
